ipld/ipld

LICENSE, README.md, contributing.md
This adds a License foe this repo, a contributing document for the entire organization, and a README filled out with content. 
I would like to add captains to each repo, too, if that is good. I can write up something about captainship as we are using it in multiformats, too. For that, I expect that I would actually be the captain for this repo, as nicola should focus on the specs and not on doing random PR merges.
=> Add Documentation to repo

README.md
Basically, I divided up the Repositories list to be more useful, mentioned current implementations, and added in a note about how to go about making new ones. This should close both #7 and #9.
=> Add Implementations to repo list

README.md
Adds a link to the IPLD explorer CLI tool and removes the link to the old deprecated one
refs #33
=> docs: add IPLD explorer CLI tool

README.md
Adding links to relevant IPFS DAG API tutorials on ProtoSchool. Part of this Q3 IPFS Docs issue: https://github.com/ProtoSchool/protoschool.github.io/issues/260
Once we separate the Decentralized Data Structures tutorial I'd link to the Merkle DAG one here as well.
=> Link to ProtoSchool tutorials on IPFS DAG API

best-practices/go-ci.md
While code coverage tools are a valuable tool during development, having code coverage aggressively enforced in CI is not a good idea: Removing a bunch of well-tested, but ultimately unnecessary code from a project would be regarded as an improvement by all developers, however, a code coverage tool would only see a drop in coverage and fail the status check on the PR.
We can use "non-blocking status checks" config from the Codecov manual: https://docs.codecov.io/docs/common-recipe-list#set-non-blocking-status-checks.
What we want the code coverage tool to do is report the changes, but to not affect the PR status. See here for a real-world example how this will look like: https://github.com/marten-seemann/codecov-test/pull/5
=> document the proper use of code coverage tools

best-practices/go-ci.md
Having Codecov comment on every PR is incredibly noise. I had assumed that the previous config we had here already prevented it from doing so, but apparently it doesn't.
cc @mvdan
=> disable Codecov code coverage comments on PR

specs/advanced-data-layouts/hamt/spec.md
This took a bit of work, but it's got the 3 commits from https://github.com/ipld/specs/pull/359, which have mostly been approved. I wouldn't mind a quick eye over the schema at the bottom which the last commit merged from two separate schemas. Is this readable enough or should I back that commit out?
I'll add a tombstone to specs for this file once this is merged.
=> data-structures: update filecoin's HAMT version

specs/advanced-data-layouts/hamt/spec.md
I CONFESS .. I didn't believe that the CI failure was genuine on #103 cause the link took me to a Fleek login page .. but it turns out the other link shows you error output and it doesn't like my named anchors.
=> fix: named anchors not linking properly

docs/schemas/index.md, specs/schemas/index.md
Crosslink schema docs and schema specs, and actually link schema specs content.
It's necessary to do the schema specs content linking manually,
because the eleventy autogen stuff we've been using for other kinds of
content only works for the markdown content pages (or stuff with
frontmatter, perhaps, but that still excludes these files).
Spartan, but makes the content reachable.  Previously it was not.
=> links to schema spec content

Makefile, package.json
We shouldn't have to touch schema-schema.ipldsch.json _unless_ we're making fundamental changes that break the JS parser.
=> Add "schema-schema" make target

_legacy/specs/data-structures/filecoin/basic_types.md, docs/schemas/features/representation-strategies.md, docs/schemas/using/authoring-guide.md, specs/schemas/schema-schema.ipldsch, specs/schemas/schema-schema.ipldsch.json
This is https://github.com/ipld/specs/pull/370, but here
---
discovered while trying to use via TypeScript @ https://github.com/ipld/js-ipld-schema/pull/37 -> https://github.com/rvagg/js-ipld-schema-validator/pull/4
=> fix: byteprefix union representation AST form fix

specs/schemas/schema-schema.ipldsch
helps with simple parsing of this doc to pull out the sections, don't lead with extra blank comment lines
very minor, and I thought we'd already done this (I have a copy in another repo that has this fix already)
=> Remove extra leading comment for consistency

.site/_includes/listing.njk, .site/css/layout.css
I originally wanted to do this just to get vertical alignment in the table fixed, but while in there I swapped the `font-size: 120%` for a `font-weight: bold` and IMO it's much more pleasant on the eyes. It also removes the "no synopsys available" since we have very few synopses in the entire site so this shows up far too much.
Thoughts?
=> clean up child listings

design/tricky-choices/dag-pb-forms-impl-and-use.md
Readable version @ https://github.com/ipld/ipld/blob/rvagg/dag-pb-investigation/design/tricky-choices/dag-pb-forms-impl-and-use.md
This relates to https://github.com/ipfs/go-ipfs/pull/7976 and is intended to help with some decision making, or at a minimum, to help build a brief summary of changes for users.
There's a lot in here but for those who are deep in this level of the stack I think it'll be informative, and we have some choices to make coming out of this.
@warpfork @aschmahmann @Stebalien @achingbrain I think you might want to all cast an eye over this. Sorry that it's so long, but there's a lot of history and implementation detail being covered! There's a couple of options outlined at the bottom for moving forward, but I'm sure there are other options we could come up with.
=> Add dag-pb investigation doc

glossary.md, specs/schemas/examples.ipldsch, specs/schemas/examples.ipldsch.json, specs/schemas/index.md, specs/schemas/prelude.md, specs/schemas/schema-schema.ipldsch, specs/schemas/schema-schema.ipldsch.json
This is... a bulk fix to every inconsistency and bug in the schema-schema I've been able to find today.
On the sad side: hooo boy, is it a diff.
On the bright side: I... think should be every fix we'll need for a good while.  It fixes every bug and nit I've accumulated a note about in the last year or more.
The diff overall may be somewhat intimidating -- especially because in the JSON form, one of the changes causes an indentation level shift -- but if you go through it commit by commit, or focus attention on the DSL (which *didn't* have an indentation change) it should be much less terrifying.
The commit log is the best reference for what happened, but also, in brief, here was my checklist as I ripped through this:
- wait, WHAT?  We didn't actually define unions as having a members …
=> Schema schema synchronization

specs/schemas/schema-schema.ipldsch
Which kind of value we have there (aka which member of AnyScalar a
parser should yield) should be obvious from the syntax.
So, quotation marks should be present for strings; for bool literals,
there should be no quotations; etc.
(If the member of AnyScalar that a parser finds doesn't actually match
the kind for the type for the field that the implicit clause is
describing, that's a logical consistency check that that should be
noticed during a "compile" phase -- not necessarily something that
the DSL parser should need to worry about.)
=> schema-schema: fix quoting typos around implicits in the DSL form.

specs/transport/car/carv2/index.md
Update CARv2 specification to include a format for MultihashIndexSorted
and fully-indexed characteristic bitfield.
Relates to:
- https://github.com/ipld/go-car/pull/239
- https://github.com/ipld/go-car/pull/217
=> Update CARv2 MultihashIndexSorted and fully-indexed characteristic spec

specs/selectors/index.md
Introduce an `ExploreInterpretAs` wrapper in selectors to allow points in a traversal where the current `Node` should be `Reified` using identified, well-known ADLs.
Example:
```
{
"~": {
"c": "unixfs",
">": { ".": {} }
}
}
```
=> Signal ADLs in selectors

specs/codecs/dag-jose/fixtures/index.md, specs/codecs/dag-jose/index.md
Time to bring dag-jose fixtures home.
The fixture data for the dag-jose itself is taken from https://github.com/ipld/codec-fixtures/pull/11/files, though I've encoded them in a slightly different way -- testmark and hexidecimal.
The other two new pieces of fixture data -- the hunk containing data model paths, and the hunk containing prettyprinted dagjson -- I have generated from the go-dag-jose implementation's current behavior.  They need to be verified for correctness!
One of my hopes here with the data model paths hunk that I've introduced is to just make it very very legible what's expected to be in the data model tree that comes out of the codec.  That hunk should be _especially_ easy to diff and be very very easy to discuss.
=> dag-jose fixtures

specs/selectors/index.md
- The prefix "Explore" on its name feels unnecessary; drop.
(Doesn't change the protocol structurally.)
- The 'as' field is no longer renamed to 'c' in the serial form.
(DOES change the protocol structurally; but there's only one
implementation of this, and we changed it too.
See https://github.com/ipld/go-ipld-prime/pull/301#discussion_r781266224.)
- Added a bunch of docs.
=> selectors: touch up InterpretAs

docs/codecs/known/dag-cbor/index.md
Expand the brief notes in the docs that overview DAG-CBOR to have more remarks on density, and add remarks on complexity.
These are thanks to a series of prompts and comments from @ianopolous.
=> docs: dag-cbor: expand remarks on density and add remarks on complexity

FAQ.md, docs/advanced-data-layouts/dynamic-loading.md, docs/advanced-data-layouts/identifying.md, docs/advanced-data-layouts/index.md, docs/advanced-data-layouts/intro.md, docs/advanced-data-layouts/known/index.md, docs/advanced-data-layouts/naming.md, docs/advanced-data-layouts/signalling.md
~(Still very much WIP.)~  Almost not WIP at all yet, but still a few blanks to fill in.
The page talking about different strategies for ADL signalling still needed some love.
This diff enumerates some more strategies, each under their own h3, and should introduce and compare them a bit better than before.
One of the key concepts is also that none of these is "the" strategy; hopefully that comes across more clearly by the time we're done here.
=> improving the ADL signalling page

README.md, docs/intro/community.md
As per https://github.com/protocol/docs/issues/9, replaces old and dull Slack and Matrix links with brand new and shiny Discord links.
=> Replaces Slack and Matrix links with Discord.

notebook/exploration-reports/2022.03-lens-combinators.md
This is a brief exploration of some ideas about how we could declaratively specify the use of Schemas, ADLs, and even have an extension path to other as-yet-uninvented data transformation mechanisms.
In it, Schemas and ADLs are both reframed as "lenses", and another new "lens" is also proposed: a simple "lens combinator", which allows invoking other lenses at various paths within some data.
Examples of using it as part of a Patch API are included, but the concept is meant to be reusable and drop-in in other scenarios as well.
=> exploration report: lens combinators

.gitignore, .site/.eleventy.js, .site/.eleventyignore, .site/.gitignore, package-lock.json, package.json
Mainly to deal with dependabot security warnings, but this is a bit overdue anyway. Updates all dependencies, the main big one being eleventy's 1.0.0 release, which has some minor breaking changes but the diff here seems to have taken care of the big ones (`sh` syntax highligher missing, .gitignore in .site no longer being read).
I ran a build, and the only material differences are some additional `<a>` elements inside headers now for named linking. Everything else seems to come out the same.
=> chore: update Eleventy and dependencies for 11ty@1.0.0

specs/advanced-data-layouts/hamt/fixture/alice-words/index.md
Fix minor typos and link to the HAMT spec from the fixture page for
convenience.
=> Fix minor typos in HAMT ADL test fixture page

specs/codecs/dag-cbor/spec.md, specs/codecs/dag-json/spec.md
Fixes: https://github.com/ipld/ipld/issues/196
Current text reflects an idealistic perspective, not a pragmatic one that
accounts for historical data and handling data from encoders that don't quite
follow the rules. Nor do the current statements requiring strictness reflect
the reality of our current decoders, which are lose and don't even yet have
full opt-in strictness modes; even though we note the lack of strictness in
the implementation notes.
=> dag-cbor,dag-json: relax strictness rules for decoders

index.njk
Closes #108 
Adds Eric's talk [Foundations for Decentralization: Data with IPLD](https://www.youtube.com/watch?v=totVQXYS1N8) as the main focus of the homepage videos
Replaces the Interplanetary OS video with the "How IPFS Deals with Files" from IPFS Camp: https://www.youtube.com/watch?v=Y_-TWTmF_1I
=> docs: Rearrange media on front page

specs/transport/car/carv2/index.md
Update the CarV2 spec table of content with link to
`MultihashIndexSorted`.
=> Add MultihashIndexSorted to table of content

docs/schemas/features/typekinds.md
Fix syntax in some cardinality examples in the schema docs.
We ditched the "default" keyword a good long time ago, and replaced it with "implicit", because we felt that better describes what it's doing.
We also introduced the parens syntax for representational annotations on a field, which is (as you can see from this diff) much terser.
This diff corrects the syntax snippet, and also adds some additional explanation prose.
=> Fix syntax in the cardinality examples in the schema docs.

.site/.eleventy.js, package-lock.json, package.json, specs/codecs/dag-eth/chain.md, specs/codecs/dag-eth/index.md
Proposed fix for : https://github.com/ipld/ipld/issues/176
I found this [11ty bug report](https://github.com/11ty/eleventy/issues/1204)  which seems to be about the same core issue. Using some of the solutions presented there as inspiration I coded up this PR which is designed to address the narrow problem of our markdown files not properly linking when accessed via GitHub web interface, or a local md-aware editor.
I have included fixups to the _md_ _files_ _themselves_ only in one area : `specs/codecs/dag-eth`. There are many more instances remaining to be changed. Figured it was best to leave them until it's clear this approach is viable.
I have manually tested the result, checking that the web site served by `yarn start` has connecting links, and the relevant pages viewed in GitHub now …
=> Fix broken .md links when viewed as markdown

specs/codecs/dag-pb/spec.md
This is shaping up to be a likely explanation for inconsistencies in Filecoin deals, with traversals yielding differently ordered blocks. I'm writing up more detailed notes on that case for an issue on https://github.com/filecoin-project/boost but the important thing here is to note that there _is_ a difference, and that we've moved almost all of the ecosystem away from sort-on-decode, but that if you want stable traversals then you shouldn't mix and match the two.
=> dag-pb: further clarifications on link sorting

specs/codecs/dag-cbor/spec.md
Corrects "limitaitons" to "limitations" in the DAG-CBOR spec page
=> DAB-CBOR Spec spelling correction

specs/codecs/dag-cbor/spec.md
Markdown links were backwards. Pretty straight-forward.
The @ipld/reviewers tag seems broken so I'm not sure if that still works and is the correct method for grabbing attention.
=> fix: fix decode strictness links in dag-cbor spec

specs/codecs/dag-cbor/spec.md
This swaps the values to match the definitions and ordering given in RFC-8949
https://datatracker.ietf.org/doc/html/rfc8949#fpnoconttbl2
I believe this was just a typo in the dag-cbor spec, and current implementations all do what RFC-8949 *actually* says (I think, I haven't checked exhaustively)
=> Update dag-cbor spec.md - swap True and False (!)

specs/selectors/fixtures/selector-fixtures-1.md, specs/selectors/index.md
Note particularly the clarifying comments in specs/selectors/index.md about how `From` and `To` work, both in relation to negative indexes and positive.
After figuring out what the underlying From and To values are, taking into account the negative value adjustments:
* A From==To matches an empty node (string or bytes)
* A From>To does not match anything
* A From<0 does not match anything
* A From>End does not match anything
Negatives will _add_ to the total length of the node, such that a `-1` value takes you to the last element of the node. But because "To" is **exclusive**, a From=-2, To=-1 matches the second last byte/character of the node. There is no way to explicitly match the final byte/character of a node, but you are allowed to overflow with the To value, so From=-1 and …
=> feat(selectors): specify negative indexes in slice matching

Makefile, docs/data-model/kinds.md, docs/data-model/pathing.md, docs/data-model/traversal.md, glossary.md
* In `make schema-schema` a space between "@" and "echo" can cause issues on older versions of `make` and it's best practice not to have it
* Removed duplicate `signalling` in Glossary
* Corrected a few typos
=> Makefile and Glosary

specs/transport/trustless-pathing/fixtures/unixfs_20m_variety.md
Does not impact usage of these tests as they just use the first column, the CID, which hasn't changed in this PR. This is cosmetic changes to match the tool which I wrote to produce these which I've since improved a little.
=> chore: more detail & cleanup execution explanations

specs/codecs/dag-cbor/spec.md
DAG-CBOR must be valid CBOR, hence the keys in maps need to be CBOR strings and not IPLD Data Model strings, which theoretically allow for arbitrary bytes.
=> fix: DAG-CBOR keys need to be CBOR strings

specs/codecs/dag-json/spec.md
In JSON numbers can be represented with the exponent notation, hence represent two identical numbers the same way, e.g. `300` as `3e2`. Add a note that for content addressing you might want to restrict it to just decimals.
---
If someone comes up with better wording please do. I just thought mentioning it at least would be good.
=> docs: add note about exponent notation to DAG-JSON

specs/codecs/dag-jose/fixtures/index.md, specs/codecs/dag-jose/spec.md
Currently dag-jose only support payloads that are *base64url* encoded CIDs. This is a problem since most JOSE tools only support signing over JSON payloads. This PR extends the dag-jose codec to support arbitrary JSON payloads.
- [js-dag-jose impl. PR](https://github.com/ceramicnetwork/js-dag-jose/pull/32)
- [rust-dag-jose (WIP) PR](https://github.com/ceramicnetwork/rust-dag-jose/pull/40)
=> DagJose JSON payload support
