- README.md
> docs: add CID inspector link

- README.md
Perhaps it should another color :)
> docs: invite folks to the IRC channel

- README.md
> Include Java implementations

- best-practices/go-ci.md
> start documenting CI best practices for Go

- events/2019-ipld-summit-berlin-notes.md
cc: @mikeal @vmx @warpfork @rvagg @aschmahmann @Raynos
I didn't catch names of other people that attended day 4, if others did could you please edit this and add them to the doc?
I've pulled together what I had, some of the notes by @warpfork that he captured (unfortunately we lost the excellent proposed ipld/schemas directory layout that was mapped out).
Please feel free to edit this branch if you have access or add your thoughts inline about some of the highlights of the discussion and add any other artifacts that you may have.
> events: add 2019 IPLD summit @ Berlin notes

- index.md
> Make a small typo correction.

- media/index.md
Like it says on the tin.
I made a brief summary here but @rvagg perhaps you'd like to tart it up better?
> Add link to Rod's RNL module recording to the media page.

- docs/synthesis/encryption/index.md
This is just a quick start, probably much more to come -- and thanks to @oed for handing me the links that primed this content.
> Start a doc page for collecting reference material about encryption.

- .site/.eleventy.js
- .site/_data/eleventyComputed.js
- .site/_data/layout.js
- .site/js/youtube-switcher.js
[JavaScript Standard Style](https://standardjs.com/) lint compatible. Other adjustments to make this easier on the modern JS programmer's eye. Also fixes a couple of bugs.
> standard.js code style, other minor clean-ups for modern idiomatic JS

- .site/.eleventy.js
- .site/_layouts/main.njk
- .site/css/prismjs@1.24-themes-prism.css
- .site/prism-ipldsch.js
- package.json
- specs/advanced-data-layouts/fbl/spec.md
> Add ipldsch syntax highlighting

- README.md
Fixed: https://github.com/ipld/ipld/issues/132
> fix(doc): fix instructions for serving

- specs/selectors/index.md
Brief explanation of how stopAt works and what can it be used for.
//cc @warpfork
> Add stopAt docs

- docs/schemas/features/representation-strategies.md
- docs/schemas/using/authoring-guide.md
- specs/schemas/schema-schema.ipldsch
- specs/schemas/schema-schema.ipldsch.json
> Add stringprefix union representation strategy

- specs/codecs/dag-jose/fixtures/index.md
All fixtures from `https://github.com/ceramicnetwork/js-dag-jose/tree/main/test/__fixtures__`
> more dag-jose fixtures

- libraries/javascript/index.md
Fixes: https://github.com/ipld/ipld/issues/140
> Add JavaScript documentation and example links

- specs/selectors/fixtures/selector-fixtures-recursion.md
Adds a new fixture file, and a fixture targeting a specific edge case in recursion.
> selectors: additional fixtures re recursion

- specs/transport/car/carv1/index.md
Docs are currently pointed at the deprecated `rvagg/js-datastore-car` instead of the new `js-car`.
Example I added is taken from the `js-car` docs—there may be a tighter/better example that'd make more sense here, not sure?
> Update JS implementation of CAR to js-car

- glossary.md
This is based on the docs for the Reify function in the Golang ADL spec and from talks with @warpfork
> Add reify to glossary

- tools/index.md
We've got all this stuff out there, and nobody knows about it :)
(Including me!  Most of these just came from discussion in the ipld community chat!  I decided to write them down before they slip out of working memory again.)
> tools: link to more web services

- README.md
Adding some minimal docs to ping @ipld/reviewers when doing pull requests.
Related to #193
> Mention reviewers team and pull requests in contributing docs

- specs/codecs/dag-json/spec.md
This is mostly existing work I did in the old ipld/specs repo but it was not ported here properly.
Closes: https://github.com/ipld/ipld/issues/160
Closes: https://github.com/ipld/ipld/issues/148
> fix: update dag-json spec with lots of clarifications

- docs/motivation/benefits-of-content-addressing.md
Here's an initial draft for adding some of the benefits of content addressing as per #208 
I've started by copying what was already mentioned in the thread and merging some of the points together.
Should some of these be elaborated on further?
Would it make sense to add some sort of conclusion to the page?
Should the intro give more info on who the target reader is? (developers that kinda understand how git works?)
> Add initial draft of benefits of content addressing doc

- tools/index.md
> Fix IPFS.io to IPFS.tech

- specs/schemas/tests/union-inline.yml
Ref: https://github.com/ipld/go-ipld-prime/issues/481
> schemas: enable union-inline test

- specs/pkg-go/trustless-pathing/testcases.go
- specs/transport/trustless-pathing/fixtures/unixfs_20m_variety.md
Ref: https://specs.ipfs.tech/http-gateways/trustless-gateway/#entity-bytes-request-query-parameter
> feat(trustless-pathing): negative byte range fixtures

- .site/.eleventyignore
- package.json
- specs/README.md
- specs/package.json
- specs/pkg-js/trustless-pathing/README.md
- specs/pkg-js/trustless-pathing/testcase.js
- specs/pkg-js/trustless-pathing/unixfs_20m_variety.js
/cc @guanzo
One problem with this is that there's no README, I need to work out if putting one in that directory is going to be a problem for site publishing. There's a README in pkg-js/trustless-pathing/ though that explains how to use that bit.
I haven't actually tried to use this, I'm doing a best-guess at what a package should look like. Care to help get it right @guanzo && @alanshaw?
> chore: publish as @ipld/specs

- specs/pkg-go/trustless-pathing/unixfs_20m_variety.go
breaking API change but the root is listed in the fixture, it comes in handy without having to parse the file
> feat!(go): return CAR root with Unixfs20mVarietyCases()

- docs/advanced-data-layouts/dynamic-loading.md
- docs/codecs/known/dag-cbor/index.md
- docs/codecs/known/index.md
- docs/intro/ecosystem.md
- docs/intro/hello-world.md
- docs/intro/primer.md
- docs/schemas/features/representation-strategies.md
- docs/schemas/features/typekinds.md
- docs/schemas/index.md
- docs/schemas/using/migrations.md
Multiple text corrections on markdown files
> Multiple text corrections

- design/libraries/index.md
- design/open-research/ADL-autoexecution.md
- design/tricky-choices/dag-pb-forms-impl-and-use.md
- design/tricky-choices/numeric-domain.md
- design/tricky-choices/ordering.md
- docs/schemas/using/authoring-guide.md
- docs/synthesis/how-ipfs-web-gateways-work.md
- specs/codecs/dag-cosmos/cosmos_state.md
- specs/codecs/dag-eth/basic_types.md
- specs/codecs/dag-eth/chain.md
- specs/codecs/dag-json/spec.md
Text corrections on several files
> Text corrections

- specs/transport/car/carv2/index.md
> A couple words helping to clarify the meaning of certain byte offsets.

- libraries/python/index.md
Adds dag-cbrrr by myself, and python-libipld by @MarshalX
> Add dag-cbrrr and python-libipld to library docs
